name: Atualizar Eventos

on:
  push:
    paths:
      - "eventos.txt"
      - "event.py"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar script de eventos
        run: python event.py

      - name: Commit arquivos JSON atualizados
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Atualização automática dos eventos"
          git push
        continue-on-error: true
